# Mushroom

In [1]:
import pandas as pd
import numpy as np

with open('agaricus-lepiota.data', 'r') as infile:
    data = pd.read_csv(infile, header = None, sep=',')
    
data[23] = data[0]
data = data.drop([0], axis=1)
data

     1  2  3  4  5  6  7  8  9  10  ... 14 15 16 17 18 19 20 21 22 23
0     x  s  n  t  p  f  c  n  k  e  ...  w  w  p  w  o  p  k  s  u  p
1     x  s  y  t  a  f  c  b  k  e  ...  w  w  p  w  o  p  n  n  g  e
2     b  s  w  t  l  f  c  b  n  e  ...  w  w  p  w  o  p  n  n  m  e
3     x  y  w  t  p  f  c  n  n  e  ...  w  w  p  w  o  p  k  s  u  p
4     x  s  g  f  n  f  w  b  k  t  ...  w  w  p  w  o  e  n  a  g  e
...  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
8119  k  s  n  f  n  a  c  b  y  e  ...  o  o  p  o  o  p  b  c  l  e
8120  x  s  n  f  n  a  c  b  y  e  ...  o  o  p  n  o  p  b  v  l  e
8121  f  s  n  f  n  a  c  b  n  e  ...  o  o  p  o  o  p  b  c  l  e
8122  k  y  n  f  y  f  c  n  b  t  ...  w  w  p  w  o  e  w  v  l  p
8123  x  s  n  f  n  a  c  b  y  e  ...  o  o  p  o  o  p  o  c  l  e

[8124 rows x 23 columns]

## construct hyperedges

In [28]:
edgePair = []
hyperedge = len(data)

for he, nodeList in data.groupby([1, 2, 3, 4]):
    for node in nodeList.index.tolist():
        edgePair.append([node, hyperedge])
    hyperedge += 1
    
for he, nodeList in data.groupby([5, 6, 7, 8, 9]):
    for node in nodeList.index.tolist():
        edgePair.append([node, hyperedge])
    hyperedge += 1

for he, nodeList in data.groupby([10, 11, 12, 13, 14, 15]):
    for node in nodeList.index.tolist():
        edgePair.append([node, hyperedge])
    hyperedge += 1

for he, nodeList in data.groupby([16, 17, 18, 19, 20]):
    for node in nodeList.index.tolist():
        edgePair.append([node, hyperedge])
    hyperedge += 1

with open('Mushroom.edges', 'w') as outfile:
    for i in edgePair:
        print ('\t'.join(list(map(str, i))), file=outfile, end = '\n')

## features

In [29]:
for i in range(1, 24, 1):
    tmpDict = {}
    for index, item in enumerate(data[i].unique().tolist()):
        tmpDict[item] = index
    data[i] = data[i].apply(lambda x: tmpDict[x])

emptyDict = {}
for i in range(23):
    emptyDict[i+1] = 0
for i in range(hyperedge):
    data = data.append(emptyDict, ignore_index=True)
with open('Mushroom.content', 'w') as outfile:
    data.to_csv(outfile, sep='\t')

data

,1,2,3,4,5,6,7,8,9,10,...,14,15,16,17,18,19,20,21,22,23
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,1,0,0,1,0,0,...,0,0,0,0,0,0,1,1,1,1
2,1,0,2,0,2,0,0,1,1,0,...,0,0,0,0,0,0,1,1,2,1
3,0,1,2,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,3,1,3,0,1,1,0,1,...,0,0,0,0,0,1,1,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16359,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16360,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16361,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16362,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16363,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Zoo

In [30]:
import pandas as pd
import numpy as np

with open('/home/chaoqiy2/github/pygcn/data/Zoo/zoo.data', 'r') as infile:
    data = pd.read_csv(infile, header = None, sep=',')

data = data.drop([0], axis=1)
data

     1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17
0     1   0   0   1   0   0   1   1   1   1   0   0   4   0   0   1   1
1     1   0   0   1   0   0   0   1   1   1   0   0   4   1   0   1   1
2     0   0   1   0   0   1   1   1   1   0   0   1   0   1   0   0   4
3     1   0   0   1   0   0   1   1   1   1   0   0   4   0   0   1   1
4     1   0   0   1   0   0   1   1   1   1   0   0   4   1   0   1   1
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
96    1   0   0   1   0   0   0   1   1   1   0   0   2   1   0   1   1
97    1   0   1   0   1   0   0   0   0   1   1   0   6   0   0   0   6
98    1   0   0   1   0   0   1   1   1   1   0   0   4   1   0   1   1
99    0   0   1   0   0   0   0   0   0   1   0   0   0   0   0   0   7
100   0   1   1   0   1   0   0   0   1   1   0   0   2   1   0   0   2

[101 rows x 17 columns]

In [31]:
edgePair = []
hyperedge = len(data)
for i in range(1, 18):
    for he, nodeList in data.groupby(i):
        if he != '?':
            for node in nodeList.index.tolist():
                edgePair.append([node, hyperedge])
            hyperedge += 1
            

with open('/home/chaoqiy2/github/pygcn/data/Zoo/zoo.edges', 'w') as outfile:
    for i in edgePair:
        print ('\t'.join(list(map(str, i))), file=outfile, end = '\n')

In [32]:
emptyDict = {}
for i in range(17):
    emptyDict[i+1] = 0
for i in range(hyperedge):
    data = data.append(emptyDict, ignore_index=True)
with open('/home/chaoqiy2/github/pygcn/data/Zoo/zoo.content', 'w') as outfile:
    data.to_csv(outfile, sep='\t')